package com.androidharness.app.data.env

import android.system.Os
import com.androidharness.app.workspace.WorkspaceFs
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.apache.commons.compress.archivers.ar.ArArchiveInputStream
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream
import org.apache.commons.compress.compressors.CompressorStreamFactory
import java.io.File
import java.io.FileOutputStream
import java.io.InputStream
import java.security.MessageDigest
import java.util.concurrent.TimeUnit
import java.util.zip.GZIPInputStream

internal const val CODEGRAPH_VERSION_MARKER = ".harness-codegraph-version"

/**
 * Where a workspace run narrates itself while it is still running. Written by
 * whichever shell tier runs the command and read back by the app, so the
 * workspace card can show progress instead of a frozen spinner.
 */
internal const val CODEGRAPH_PROGRESS_LOG = ".harness-progress.log"

private const val PROGRESS_POLL_MS = 400L

/** Keeps the live log to the last screen or so, however long the run gets. */
private const val PROGRESS_TAIL_CHARS = 2_000

private fun shellQuote(value: String): String = "'" + value.replace("'", "'\\''") + "'"

internal object CodeGraphCommands {
    private fun quote(value: String): String = "'" + value.replace("'", "'\\''") + "'"

    const val version = "codegraph --no-color version"
    // A full build is minutes long on a real project, and --verbose is what
    // makes it narrate: a line per phase plus a count every few percent, all
    // plain text because the run's stdout is a file rather than a terminal.
    const val init = "codegraph --no-color init --yes --verbose ."
    const val sync = "codegraph --no-color sync ."
    const val reindex = "codegraph --no-color index --verbose ."
    const val uninit = "codegraph --no-color uninit --force ."

    fun explore(query: String): String = "codegraph --no-color explore ${quote(query)}"

    fun node(name: String?, file: String?, offset: Int?, limit: Int?): String = buildString {
        append("codegraph --no-color node")
        if (!file.isNullOrBlank()) append(" --file ").append(quote(file.trim()))
        if (offset != null) append(" --offset ").append(offset.coerceAtLeast(1))
        if (limit != null) append(" --limit ").append(limit.coerceIn(1, 2_000))
        if (!name.isNullOrBlank()) append(' ').append(quote(name.trim()))
    }

    fun impact(symbol: String, depth: Int): String =
        "codegraph --no-color impact --depth ${depth.coerceIn(1, 10)} ${quote(symbol.trim())}"

    fun affected(files: List<String>, depth: Int): String = buildString {
        append("codegraph --no-color affected --depth ").append(depth.coerceIn(1, 10))
        files.map { it.trim() }.filter { it.isNotEmpty() }.forEach { append(' ').append(quote(it)) }
    }

    /**
     * The `codegraph` entry point Harness installs into the prefix. The
     * upstream release archive bundles its own Node, but that binary is built
     * against glibc and cannot start on Android, so the launcher runs the
     * archive's JavaScript on the Termux-built Node 24 installed beside it.
     *
     * $0-relative on purpose: the same file is used from the app-private
     * prefix and from the shell-tier copy deployed under /data/local/tmp, and
     * only the first is known at write time. ELF exec is blocked for
     * app-private files, so the dynamic linker runs the runtime when present.
     */
    fun launcher(): String = """
        |#!/system/bin/sh
        |# auto-generated by AndroidHarness: runs CodeGraph's JS on the bundled Node 24.
        |case "${'$'}0" in
        |  */*) DIR="${'$'}{0%/*}" ;;
        |  *) DIR="." ;;
        |esac
        |PREFIX="${'$'}(cd "${'$'}DIR/.." && pwd)"
        |NODE="${'$'}PREFIX/codegraph/node/bin/node"
        |CLI="${'$'}PREFIX/codegraph/bundle/lib/dist/bin/codegraph.js"
        |if [ ! -f "${'$'}CLI" ] || [ ! -x "${'$'}NODE" ]; then
        |  echo "codegraph: the Harness-installed runtime is incomplete. Reinstall it from Settings, Code intelligence." >&2
        |  exit 127
        |fi
        |# CodeGraph ships anonymous usage telemetry that is ON by default, and its
        |# resolution order is DO_NOT_TRACK > CODEGRAPH_TELEMETRY > stored config,
        |# so both are set here: nothing is recorded, nothing is sent, no socket is
        |# opened, and a config an earlier run left behind cannot turn it back on.
        |# Harness ships a telemetry-free install and does not re-enable it.
        |DO_NOT_TRACK=1
        |CODEGRAPH_TELEMETRY=0
        |export DO_NOT_TRACK CODEGRAPH_TELEMETRY
        |# Node opens the openssl.cnf it was built with, which for these Termux
        |# builds is /data/data/com.termux/...: unreadable from this app, and when
        |# the Termux app is installed that is EACCES rather than a missing file,
        |# so Node exits instead of starting. Point it at the copy in this prefix.
        |if [ -f "${'$'}PREFIX/${com.androidharness.app.tools.NetTls.OPENSSL_CONF_RELATIVE_PATH}" ]; then
        |  OPENSSL_CONF="${'$'}PREFIX/${com.androidharness.app.tools.NetTls.OPENSSL_CONF_RELATIVE_PATH}"
        |  export OPENSSL_CONF
        |fi
        |LINKER=
        |for c in /system/bin/linker64 /apex/com.android.runtime/bin/linker64 /system/bin/linker; do
        |  if [ -x "${'$'}c" ]; then LINKER="${'$'}c"; break; fi
        |done
        |if [ -n "${'$'}LINKER" ]; then
        |  # Started through the linker, Node reports the LINKER as process.execPath,
        |  # so anything that re-runs Node through that path is malformed. CodeGraph's
        |  # liveness watchdog does exactly that ("node -e") and prints
        |  # 'expected absolute path: "-e"' while its daemon safety net fails to
        |  # start. Harness owns the child process lifetime, so turn it off.
        |  CODEGRAPH_NO_WATCHDOG=1
        |  export CODEGRAPH_NO_WATCHDOG
        |  exec "${'$'}LINKER" "${'$'}NODE" --liftoff-only --disable-warning=ExperimentalWarning "${'$'}CLI" "${'$'}@"
        |fi
        |exec "${'$'}NODE" --liftoff-only --disable-warning=ExperimentalWarning "${'$'}CLI" "${'$'}@"
        |""".trimMargin()
}

/**
 * Everything about *where* CodeGraph comes from.
 *
 * Android is not a published CodeGraph platform: the npm shim asks for
 * `codegraph-android-arm64` because Termux's Node reports `process.platform
 * == "android"`, and neither npm nor GitHub Releases ever publishes it
 * (colbymchenry/codegraph#1550). So Harness does not use npm at all here. It
 * takes the linux-arm64 release archive and keeps only the parts that carry
 * no platform assumption, the JavaScript and the tree-sitter WASM grammars,
 * plus the Termux-built Node that can actually run them.
 */
internal object CodeGraphProvision {
    private const val REPO = "colbymchenry/codegraph"

    /** The release archive whose payload is architecture-independent. */
    const val BUNDLE_ASSET = "codegraph-linux-arm64.tar.gz"

    /** Checksums published next to the archive, best effort. */
    const val SUMS_ASSET = "SHA256SUMS"

    /** Termux package carrying the Node 24 runtime CodeGraph is built against. */
    const val NODE_PACKAGE = "nodejs-lts"

    fun latestPageUrl(): String = "https://github.com/$REPO/releases/latest"

    fun releasesPageUrl(): String = "https://github.com/$REPO/releases"

    fun apiLatestUrl(): String = "https://api.github.com/repos/$REPO/releases/latest"

    /** Release feed: unrated, and served from the same host as the archives. */
    fun atomUrl(): String = "https://github.com/$REPO/releases.atom"

    /** Registry metadata, on a host that has nothing to do with GitHub. */
    fun registryUrl(): String = "https://registry.npmjs.org/@colbymchenry/codegraph/latest"

    /**
     * The newest archive without naming a tag: GitHub resolves `latest` on the
     * same host the archives are served from. This is how an install gets its
     * files, so a release that cannot be *named* can still be installed.
     */
    fun latestAssetUrl(): String = "https://github.com/$REPO/releases/latest/download/$BUNDLE_ASSET"

    fun latestSumsUrl(): String = "https://github.com/$REPO/releases/latest/download/$SUMS_ASSET"

    /**
     * Release tag named by a URL: a redirect target, or a link inside a page.
     * The tag has to look like a version, so an unrelated path segment in a
     * page full of links is never mistaken for one.
     */
    fun tagFromUrl(url: String?): String? {
        val raw = url?.let { Regex("""/releases/(?:tag|download)/([^/?#"'\s]+)""").find(it)?.groupValues?.get(1) }
        return raw?.takeIf { it.trimStart('v').firstOrNull()?.isDigit() == true }?.let(::normalizeTag)
    }

    /** Newest tag named in a releases page, which lists the latest release first. */
    fun tagFromPage(html: String): String? = tagFromUrl(html)

    /** Version from registry metadata, shaped as `"version": "1.6.0"`. */
    fun tagFromManifest(json: String): String? =
        Regex("\"version\"\\s*:\\s*\"([^\"]+)\"").find(json)?.groupValues?.get(1)?.let(::normalizeTag)

    /**
     * Release tag from the releases Atom feed's newest entry. The entry title
     * is whatever the release was called, so a version-shaped token is pulled
     * out of it rather than trusting the title to be the tag verbatim.
     */
    fun tagFromAtom(xml: String): String? {
        val entry = Regex("<entry>(.*?)</entry>", RegexOption.DOT_MATCHES_ALL).find(xml)
            ?.groupValues?.get(1) ?: return null
        val title = Regex("<title>(.*?)</title>", RegexOption.DOT_MATCHES_ALL).find(entry)
            ?.groupValues?.get(1) ?: return null
        return Regex("""v?\d+\.\d+\.\d+(?:[-+][A-Za-z0-9._-]+)?""").find(title)?.value
    }

    /** Release tag from the API's `tag_name` field. */
    fun tagFromApi(json: String): String? =
        Regex("\"tag_name\"\\s*:\\s*\"([^\"]+)\"").find(json)?.groupValues?.get(1)?.trim()?.takeIf { it.isNotEmpty() }

    /** Release tags are `vX.Y.Z`; accept a bare `X.Y.Z` too. */
    fun normalizeTag(raw: String?): String? {
        val tag = raw?.trim()?.takeIf { it.isNotEmpty() } ?: return null
        return if (tag.startsWith("v")) tag else "v$tag"
    }

    /**
     * The bare X.Y.Z in a tag or in CodeGraph's own version output, which is
     * the form the version marker stores. The leading `v` is optional and
     * stripped, and it cannot be fenced with `\b`: there is no word boundary
     * between the `v` and the digit that follows it, so a tag would never
     * match its own version.
     */
    fun versionIn(text: String?): String? =
        text?.let { Regex("""v?\d+\.\d+\.\d+(?:[-+][A-Za-z0-9._-]+)?""").find(it)?.value?.removePrefix("v") }

    /** Expected SHA-256 of [asset] from a published SHA256SUMS file, or null when unlisted. */
    fun sha256For(sums: String, asset: String): String? = sums.lineSequence().mapNotNull { line ->
        val match = Regex("^([0-9a-fA-F]{64})\\s+\\*?(.+)$").find(line.trim()) ?: return@mapNotNull null
        if (match.groupValues[2].trim().substringAfterLast('/') == asset) match.groupValues[1].lowercase() else null
    }.firstOrNull()

    /**
     * Body for CodeGraph's stored telemetry consent, with telemetry off. The
     * file is `$HOME/.codegraph/telemetry.json` and it is what
     * `codegraph telemetry off` writes, so an install that was never given our
     * launcher cannot report either. Any machine_id already on disk is kept:
     * rewriting it would look like a new machine to the (disabled) collector.
     */
    fun telemetryOffConfig(existing: String?, machineId: String): String {
        val kept = Regex("\"machine_id\"\\s*:\\s*\"([^\"]+)\"").find(existing.orEmpty())?.groupValues?.get(1)
        return """
            {
              "enabled": false,
              "machine_id": "${kept ?: machineId}",
              "consent_source": "androidharness",
              "first_run_notice_shown": true,
              "updated_at": "${java.time.Instant.now()}"
            }
        """.trimIndent()
    }

    /** True when [existing] already records telemetry as off. */
    fun telemetryIsOff(existing: String?): Boolean =
        Regex("\"enabled\"\\s*:\\s*false").containsMatchIn(existing.orEmpty())

    /** True when [candidate] is a later release than [installed], ignoring any pre-release suffix. */
    fun isNewer(candidate: String, installed: String): Boolean {
        fun parts(v: String) = v.substringBefore('-').substringBefore('+')
            .split('.').map { it.trim().toIntOrNull() ?: 0 }
        val a = parts(candidate)
        val b = parts(installed)
        for (i in 0 until maxOf(a.size, b.size)) {
            val diff = (a.getOrNull(i) ?: 0) - (b.getOrNull(i) ?: 0)
            if (diff != 0) return diff > 0
        }
        return false
    }

    /**
     * Prefix-relative path for a release archive entry worth keeping, or null
     * to skip it. The archive's own Node (`node`, ~116 MB, glibc) and native
     * kernel (`lib/kernel`, glibc) are dropped: the kernel is optional by
     * design and extraction falls back to the WASM grammars without it.
     * Sourcemaps and type declarations are development-only.
     */
    fun portablePath(entry: String): String? {
        val cleaned = entry.trim().removePrefix("./").removePrefix("/")
        if (cleaned.isEmpty()) return null
        // Validate every segment BEFORE dropping the archive's top-level
        // directory: checking afterwards would let "../lib/x" collapse into a
        // harmless-looking "lib/x" and escape the destination.
        val segments = cleaned.split('/')
        if (segments.any { it.isEmpty() || it == "." || it == ".." }) return null
        // Entries carry that directory, e.g. "codegraph-linux-arm64/lib/dist/index.js".
        val rel = segments.drop(1).joinToString("/")
        if (!rel.startsWith("lib/")) return null
        if (rel.startsWith("lib/kernel/")) return null
        if (rel.endsWith(".map") || rel.endsWith(".d.ts")) return null
        return rel
    }
}

data class CodeGraphState(
    val version: String? = null,
    /** Newest published release, once a check has run. */
    val latest: String? = null,
    val busy: Boolean = false,
    val action: String? = null,
    val message: String? = null,
    val failed: Boolean = false,
) {
    val updateAvailable: Boolean
        get() = version != null && latest != null && CodeGraphProvision.isNewer(latest, version)
}

data class CodeGraphCommandResult(val ok: Boolean, val output: String)

/**
 * A run against one workspace. Kept apart from [CodeGraphState] so the output
 * of a sync shows up in the workspace card that asked for it, instead of in
 * the install card at the top of the page.
 */
data class CodeGraphRunState(
    val busy: Boolean = false,
    val action: String? = null,
    val message: String? = null,
    val failed: Boolean = false,
)

class CodeGraphManager(
    private val linuxEnv: LinuxEnvironmentManager,
    private val shellRouter: ShellTierRouter,
) {
    private val mcp = CodeGraphMcp(linuxEnv)

    suspend fun agentTools(workspace: WorkspaceFs): List<com.androidharness.app.tools.Tool> =
        mcp.tools(workspace) { isAvailable(workspace) }

    // Release archives run to ~130 MB, so the read timeout is generous: the
    // call timeout is what bounds a genuinely stalled connection.
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(5, TimeUnit.MINUTES)
        .callTimeout(30, TimeUnit.MINUTES)
        .build()

    /**
     * Metadata requests are small and can be tried against several hosts in a
     * row, so they get a timeout that stops a dead network from turning a
     * version check into a minute of spinning.
     */
    private val lookupClient = OkHttpClient.Builder()
        .connectTimeout(10, TimeUnit.SECONDS)
        .readTimeout(15, TimeUnit.SECONDS)
        .callTimeout(20, TimeUnit.SECONDS)
        .build()

    private val marker get() = File(linuxEnv.prefix, CODEGRAPH_VERSION_MARKER)
    private val binary get() = File(linuxEnv.prefix, "bin/codegraph")
    private val home get() = File(linuxEnv.prefix, "home").apply { mkdirs() }
    private val root get() = File(linuxEnv.prefix, "codegraph")
    private val nodeBinary get() = File(root, "node/bin/node")
    private val bundleLib get() = File(root, "bundle/lib")

    /** The bundle's JavaScript, which is what the Harness patches edit. */
    private val bundleDist get() = File(bundleLib, "dist")

    /**
     * Unpatched copy of `lib/dist` kept at provision time. When the live copy
     * is a hybrid no patch generation recognises, the self-heal restores the
     * patchable files from here instead of leaving the hybrid in place.
     */
    private val pristineDist get() = File(root, "bundle.pristine/lib/dist")

    private val _state = MutableStateFlow(CodeGraphState(version = markerVersion()))
    val state: StateFlow<CodeGraphState> = _state

    private val _workspaceState = MutableStateFlow(CodeGraphRunState())
    val workspaceState: StateFlow<CodeGraphRunState> = _workspaceState

    /** Set once the on-disk launcher has been compared with this build's. */
    @Volatile
    private var launcherChecked = false
    private var bundlePatchChecked = false

    fun isIndexed(workspace: WorkspaceFs?): Boolean =
        workspace?.shellRoot?.resolve(".codegraph")?.isDirectory == true

    fun isAvailable(workspace: WorkspaceFs): Boolean {
        if (workspace is com.androidharness.app.workspace.SshFs) return true
        if (!linuxEnv.isReady || !binary.exists() || !isIndexed(workspace)) return false
        ensureLauncherCurrent()
        return true
    }

    suspend fun refresh(): CodeGraphState {
        if (!binary.exists() || !linuxEnv.isReady) {
            marker.delete()
            val next = CodeGraphState()
            _state.value = next
            return next
        }
        ensureLauncherCurrent()
        val result = run(CodeGraphCommands.version, home, 30_000, 4_000)
        val version = if (result.ok) parseVersion(result.output) else null
        if (version != null) marker.writeText(version) else marker.delete()
        val next = _state.value.copy(
            version = version,
            message = if (result.ok) null else result.output.ifBlank { "CodeGraph could not be started." },
            failed = !result.ok,
        )
        _state.value = next
        return next
    }

    /**
     * Asks GitHub for the newest release and compares it with what is
     * installed, so the settings page can offer an update only when there is
     * one. Reports the outcome in [CodeGraphState.message] either way, which
     * is what makes an explicit "check" tap answer "already latest".
     */
    suspend fun checkForUpdates(): CodeGraphState {
        val installed = _state.value.version ?: return _state.value
        _state.value = _state.value.copy(busy = true, action = "Checking for updates", message = null, failed = false)
        val lookup = withContext(Dispatchers.IO) { lookUpLatestRelease() }
        // A tag is a URL component ("v1.6.0"), the version marker holds what
        // CodeGraph itself reports ("1.6.0"), so compare in the marker's form.
        val latest = CodeGraphProvision.versionIn(lookup.tag)
        val next = _state.value.copy(
            busy = false,
            action = null,
            latest = latest ?: _state.value.latest,
            message = when {
                latest != null && CodeGraphProvision.isNewer(latest, installed) -> "CodeGraph $latest is available."
                latest != null -> "CodeGraph $installed is the latest version."
                // The tag came back but was unreadable, which is not a network
                // problem and must not be reported as one.
                lookup.tag != null -> "Found CodeGraph ${lookup.tag}, but its version could not be read."
                else -> "Could not check for updates (${lookup.problem ?: "no release found"})."
            },
            failed = latest == null,
        )
        _state.value = next
        return next
    }

    suspend fun installOrUpdate(): CodeGraphState = busy("Installing CodeGraph") {
        // The download, the unpack and the hashing all block, and this is
        // reached from the Settings UI's Main-dispatcher scope.
        val failure = withContext(Dispatchers.IO) { provision() }
        if (failure != null) return@busy failure
        val verified = run(CodeGraphCommands.version, home, 60_000, 4_000)
        if (!verified.ok) return@busy verified
        val version = parseVersion(verified.output)
            ?: return@busy CodeGraphCommandResult(false, "CodeGraph installed, but its version could not be verified.")
        marker.writeText(version)
        // Just installed the newest release, so the update check has its answer
        // until the next one lands.
        _state.value = _state.value.copy(latest = version)
        linuxEnv.invalidateExternalToolDeploy()
        CodeGraphCommandResult(true, "CodeGraph $version installed.")
    }

    /** Downloads and lays out the runtime. Null on success, else the failure to report. */
    private suspend fun provision(): CodeGraphCommandResult? {
        linuxEnv.install(listOf("bash"))
        if (!linuxEnv.isReady) {
            return CodeGraphCommandResult(false, "The Linux environment could not be prepared.")
        }
        val work = File(linuxEnv.appPrivateScratch, "codegraph").apply { mkdirs() }
        val archive = File(work, CodeGraphProvision.BUNDLE_ASSET)
        try {
            // GitHub resolves "latest" itself, so an install never waits on
            // naming the release first, and never fails because a metadata
            // request did.
            setAction("Preparing the CodeGraph download")
            // Best effort, like upstream's installer: a missing SHA256SUMS
            // never blocks an install, a published one always wins.
            val expected = runCatching { fetchText(CodeGraphProvision.latestSumsUrl(), lookupClient) }
                .getOrNull()
                ?.let { CodeGraphProvision.sha256For(it, CodeGraphProvision.BUNDLE_ASSET) }
            setAction("Downloading CodeGraph")
            download(CodeGraphProvision.latestAssetUrl(), archive, expected) { percent ->
                setAction("Downloading CodeGraph ($percent%)")
            }
            setAction("Unpacking CodeGraph")
            extractBundle(archive)
        } catch (ce: kotlinx.coroutines.CancellationException) {
            throw ce
        } catch (e: Exception) {
            return CodeGraphCommandResult(false, e.message ?: "Installing CodeGraph failed.")
        } finally {
            archive.delete()
        }

        if (!File(bundleLib, "dist/bin/codegraph.js").isFile) {
            return CodeGraphCommandResult(false, "The CodeGraph archive did not contain its CLI.")
        }
        setAction("Preparing the CodeGraph runtime")
        if (!ensureNodeRuntime()) {
            return CodeGraphCommandResult(false, "Could not install the Node runtime CodeGraph needs.")
        }
        writeLauncher()
        // A fresh download is the unpatched release, so the fixes go on before
        // anything can run it. A pristine copy of the patchable files is kept
        // beside the bundle so the per-launch patch pass can self-heal a copy
        // that several patch generations left in an unrecognisable state.
        runCatching {
            val pristine = pristineDist
            pristine.deleteRecursively()
            pristine.mkdirs()
            for (rel in CodeGraphBundlePatches.patchedFiles) {
                val src = File(bundleDist, rel)
                if (!src.isFile) continue
                val dst = File(pristine, rel)
                dst.parentFile?.mkdirs()
                src.copyTo(dst, overwrite = true)
            }
        }
        CodeGraphBundlePatches.apply(bundleDist)
        ensureTelemetryOff()
        removeLegacyNpmInstall()
        linuxEnv.ensureShims(force = true)
        return null
    }

    suspend fun uninstall(): CodeGraphState = busy("Uninstalling CodeGraph") {
        val existed = binary.exists() || root.exists()
        withContext(Dispatchers.IO) {
            runCatching { root.deleteRecursively() }
            runCatching { binary.delete() }
            removeLegacyNpmInstall()
            marker.delete()
            linuxEnv.ensureShims(force = true)
        }
        linuxEnv.invalidateExternalToolDeploy()
        CodeGraphCommandResult(true, if (existed) "CodeGraph removed." else "CodeGraph is not installed.")
    }

    suspend fun initWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.init, "Initialize CodeGraph")

    suspend fun syncWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.sync, "Sync CodeGraph")

    suspend fun reindexWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.reindex, "Re-index CodeGraph", timeoutMs = 300_000)

    suspend fun disableWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.uninit, "Disable CodeGraph")

    suspend fun explore(workspace: WorkspaceFs, query: String): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.explore(query))

    suspend fun node(
        workspace: WorkspaceFs,
        name: String?,
        file: String?,
        offset: Int?,
        limit: Int?,
    ): CodeGraphCommandResult = queryWorkspace(workspace, CodeGraphCommands.node(name, file, offset, limit))

    suspend fun impact(workspace: WorkspaceFs, symbol: String, depth: Int): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.impact(symbol, depth))

    suspend fun affected(workspace: WorkspaceFs, files: List<String>, depth: Int): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.affected(files, depth))

    // ------------------------------------------------------------------
    // Provisioning
    // ------------------------------------------------------------------

    /** Newest published release, or why it could not be resolved. */
    private data class ReleaseLookup(val tag: String?, val problem: String?)

    /**
     * Resolves the newest release from several sources, cheapest and most
     * reliable first. Each failure is kept, because a bare "could not reach
     * GitHub" hides whether that was DNS, a rate limit or an unexpected
     * response, and the settings page shows the reason.
     */
    private fun lookUpLatestRelease(): ReleaseLookup {
        val problems = mutableListOf<String>()

        // 1. releases/latest, without following: the Location header names the
        //    tag, on the same host the archives download from, and no API
        //    quota is involved.
        runCatching {
            client.newBuilder().followRedirects(false).build()
                .newCall(Request.Builder().url(CodeGraphProvision.latestPageUrl()).build())
                .execute().use { response ->
                    CodeGraphProvision.tagFromUrl(response.header("Location"))
                        ?.let { return ReleaseLookup(it, null) }
                    problems += "redirect HTTP ${response.code}"
                }
        }.onFailure { problems += "redirect ${it.reason()}" }

        // 2. The same page followed to the end: if the header is missing the
        //    tag is still in the URL the request landed on, or in the page.
        runCatching {
            lookupClient.newCall(Request.Builder().url(CodeGraphProvision.latestPageUrl()).build())
                .execute().use { response ->
                    CodeGraphProvision.tagFromUrl(response.request.url.toString())
                        ?.let { return ReleaseLookup(it, null) }
                    CodeGraphProvision.tagFromPage(response.body?.string().orEmpty())
                        ?.let { return ReleaseLookup(it, null) }
                    problems += "release page HTTP ${response.code}"
                }
        }.onFailure { problems += "release page ${it.reason()}" }

        // 3. The releases page, which lists the newest tag first.
        runCatching {
            CodeGraphProvision.tagFromPage(fetchText(CodeGraphProvision.releasesPageUrl(), lookupClient))
                ?.let { return ReleaseLookup(it, null) }
            problems += "releases page had no tag"
        }.onFailure { problems += "releases page ${it.reason()}" }

        // 4. The feed: unrated, served from the same host as the archives.
        runCatching {
            CodeGraphProvision.tagFromAtom(fetchText(CodeGraphProvision.atomUrl(), lookupClient))
                ?.let { return ReleaseLookup(it, null) }
            problems += "feed had no release"
        }.onFailure { problems += "feed ${it.reason()}" }

        // 5. The registry, on an unrelated host.
        runCatching {
            CodeGraphProvision.tagFromManifest(fetchText(CodeGraphProvision.registryUrl(), lookupClient))
                ?.let { return ReleaseLookup(it, null) }
            problems += "registry had no version"
        }.onFailure { problems += "registry ${it.reason()}" }

        // 6. The API last: it is rate limited per IP, so it is the one most
        //    likely to answer 403 on a shared or carrier connection.
        runCatching {
            CodeGraphProvision.tagFromApi(fetchText(CodeGraphProvision.apiLatestUrl(), lookupClient))
                ?.let { return ReleaseLookup(it, null) }
            problems += "api had no tag"
        }.onFailure { problems += "api ${it.reason()}" }

        return ReleaseLookup(null, problems.joinToString("; "))
    }

    /** Short, readable form of a failure, for the one line the settings page shows. */
    private fun Throwable.reason(): String =
        message?.takeIf { it.isNotBlank() } ?: javaClass.simpleName

    private fun fetchText(url: String, on: OkHttpClient = client): String =
        on.newCall(Request.Builder().url(url).build()).execute().use { response ->
            if (!response.isSuccessful) throw IllegalStateException("HTTP ${response.code} fetching $url")
            response.body?.string() ?: throw IllegalStateException("Empty response from $url")
        }

    private fun download(url: String, dest: File, expectedSha256: String?, onProgress: (Int) -> Unit) {
        dest.parentFile?.mkdirs()
        client.newCall(Request.Builder().url(url).build()).execute().use { response ->
            if (!response.isSuccessful) throw IllegalStateException("HTTP ${response.code} downloading $url")
            val body = response.body ?: throw IllegalStateException("Empty download from $url")
            val total = body.contentLength()
            val digest = MessageDigest.getInstance("SHA-256")
            var read = 0L
            dest.outputStream().use { out ->
                body.byteStream().use { input ->
                    val buf = ByteArray(128 * 1024)
                    while (true) {
                        val n = input.read(buf)
                        if (n < 0) break
                        out.write(buf, 0, n)
                        digest.update(buf, 0, n)
                        read += n
                        if (total > 0) onProgress(((read * 100) / total).toInt())
                    }
                }
            }
            val actual = digest.digest().joinToString("") { "%02x".format(it) }
            if (expectedSha256 != null && !actual.equals(expectedSha256, ignoreCase = true)) {
                dest.delete()
                throw IllegalStateException("Checksum mismatch for ${dest.name}")
            }
        }
    }

    /** Unpacks the portable half of the release archive and swaps it in atomically. */
    private fun extractBundle(archive: File) {
        val staging = File(root, "bundle.new").apply {
            deleteRecursively()
            mkdirs()
        }
        GZIPInputStream(archive.inputStream().buffered()).use { gz ->
            TarArchiveInputStream(gz).use { tar ->
                while (true) {
                    val entry = tar.nextTarEntry ?: break
                    if (entry.isDirectory || entry.isSymbolicLink) continue
                    val rel = CodeGraphProvision.portablePath(entry.name) ?: continue
                    val target = File(staging, rel)
                    target.parentFile?.mkdirs()
                    FileOutputStream(target).use { out -> tar.copyTo(out) }
                    runCatching { Os.chmod(target.absolutePath, entry.mode and 0xFFF) }
                }
            }
        }
        val live = File(root, "bundle")
        val previous = File(root, "bundle.old")
        previous.deleteRecursively()
        if (live.exists()) live.renameTo(previous)
        if (!staging.renameTo(live)) throw IllegalStateException("Could not activate the CodeGraph bundle.")
        previous.deleteRecursively()
    }

    /**
     * Installs the Node runtime CodeGraph runs on, when the prefix has none.
     * Termux's `nodejs-lts` is Node 24, the version the release bundle embeds
     * and the newest CodeGraph accepts: it refuses to start on the 25+ that
     * the prefix's `nodejs` package ships, over a V8 WASM crash it cannot
     * guard against. Extracted on its own instead of installed as a package
     * because it conflicts with that `nodejs`.
     */
    private suspend fun ensureNodeRuntime(): Boolean {
        if (nodeBinary.isFile && nodeBinary.length() > 0) return true
        val work = File(linuxEnv.appPrivateScratch, "codegraph").apply { mkdirs() }
        val deb = File(work, "nodejs-lts.deb")
        return try {
            if (!linuxEnv.downloadPackageDeb(CodeGraphProvision.NODE_PACKAGE, deb)) return false
            extractNodeBinary(deb)
            nodeBinary.isFile && nodeBinary.length() > 0
        } finally {
            deb.delete()
        }
    }

    private fun extractNodeBinary(deb: File) {
        ArArchiveInputStream(deb.inputStream().buffered()).use { ar ->
            var entry = ar.nextEntry
            while (entry != null && !entry.name.startsWith("data.tar")) entry = ar.nextEntry
            if (entry == null) throw IllegalStateException("No data archive in ${deb.name}")
            // Choose the decompressor from the extension, since auto-detection
            // would need a markable stream, which ArArchiveInputStream is not.
            val name = entry.name
            val input: InputStream = when {
                name.endsWith(".xz") || name.endsWith(".lzma") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.XZ, ar)
                name.endsWith(".gz") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.GZIP, ar)
                name.endsWith(".bz2") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.BZIP2, ar)
                name.endsWith(".zst") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.ZSTANDARD, ar)
                else -> ar
            }
            TarArchiveInputStream(input).use { tar ->
                while (true) {
                    val e = tar.nextTarEntry ?: break
                    val rel = e.name.removePrefix("./").removePrefix("/")
                    if (rel != "data/data/com.termux/files/usr/bin/node") continue
                    nodeBinary.parentFile?.mkdirs()
                    FileOutputStream(nodeBinary).use { out -> tar.copyTo(out) }
                    runCatching { Os.chmod(nodeBinary.absolutePath, 0x1ED) } // 0755
                }
            }
        }
    }

    private fun writeLauncher() {
        binary.parentFile?.mkdirs()
        // The npm-based install left a symlink here pointing into its package;
        // writing straight to the path would follow it and clobber that file.
        runCatching { binary.delete() }
        binary.writeText(CodeGraphCommands.launcher())
        runCatching { Os.chmod(binary.absolutePath, 0x1ED) } // 0755
    }

    /**
     * Rewrites the entry point when it predates this build, so a fix to the
     * launcher (the runtime flags, the OpenSSL config) reaches an install that
     * already exists instead of waiting for a reinstall. Once per process: the
     * compare is small but not free, and the launcher cannot change under us.
     */
    private fun ensureLauncherCurrent() {
        ensureBundlePatched()
        if (launcherChecked || !binary.exists()) return
        launcherChecked = true
        var changed = false
        if (runCatching { binary.readText() }.getOrNull() != CodeGraphCommands.launcher()) {
            writeLauncher()
            changed = true
        }
        if (ensureTelemetryOff()) changed = true
        // The staged tarball is only rewritten when it looks stale, so a change
        // made here would otherwise sit in the app prefix and never reach the
        // deployed copy that the privileged tier runs.
        if (changed) linuxEnv.invalidateExternalToolDeploy()
    }

    /**
     * Applies the fixes Harness carries for the vendored CodeGraph release.
     * Runs once per process, on the same path that keeps the launcher and the
     * telemetry config current, so an install that already exists picks them up
     * instead of waiting for a reinstall.
     *
     * A copy whose state no patch generation fully recognises (installations
     * that lived through several patch generations can be a mix) is restored
     * file-by-file from the pristine snapshot taken at provision time and
     * patched again, so an unknown hybrid state converges instead of
     * persisting on the device forever.
     */
    private fun ensureBundlePatched() {
        if (bundlePatchChecked) return
        bundlePatchChecked = true
        var result = runCatching { CodeGraphBundlePatches.apply(bundleDist) }.getOrNull() ?: return
        if (result.unresolved.isNotEmpty()) {
            val pristine = pristineDist
            if (pristine.isDirectory) {
                var restored = false
                for (rel in CodeGraphBundlePatches.patchedFiles) {
                    val src = File(pristine, rel)
                    if (!src.isFile) continue
                    val dst = File(bundleDist, rel)
                    if (dst.isFile && runCatching { src.copyTo(dst, overwrite = true) }.isSuccess) restored = true
                }
                if (restored) {
                    result = runCatching { CodeGraphBundlePatches.apply(bundleDist) }.getOrNull() ?: result
                }
            }
        }
        // The staged tarball is only rewritten when it looks stale, so a change
        // to the bundle has to invalidate it or the privileged tier keeps
        // running the copy it deployed before the fix.
        if (result.changed) linuxEnv.invalidateExternalToolDeploy()
    }

    /**
     * Turns CodeGraph's anonymous usage telemetry off on disk, so a launch that
     * bypasses the launcher (someone running the bundle's JS directly) cannot
     * report either. The launcher sets the env vars that outrank this file; both
     * exist because the env only covers processes it starts.
     */
    private fun ensureTelemetryOff(): Boolean {
        val config = File(home, ".codegraph/telemetry.json")
        val existing = runCatching { config.readText() }.getOrNull()
        if (CodeGraphProvision.telemetryIsOff(existing)) return false
        return runCatching {
            config.parentFile?.mkdirs()
            config.writeText(
                CodeGraphProvision.telemetryOffConfig(existing, java.util.UUID.randomUUID().toString()),
            )
            // "Off is off": drop whatever was buffered but not yet sent.
            File(config.parentFile, "telemetry-queue.jsonl").delete()
            true
        }.getOrDefault(false)
    }

    /**
     * Removes what the earlier npm-based install left behind. That route could
     * never work on Android (there is no `codegraph-android-arm64` bundle to
     * install) and the launcher now replaces its entry point, so the shim
     * package is dead weight.
     */
    private fun removeLegacyNpmInstall() {
        runCatching { File(linuxEnv.prefix, "lib/node_modules/@colbymchenry").deleteRecursively() }
    }

    /** Current step, shown under the progress bar while an install runs. */
    private fun setAction(action: String) {
        _state.value = _state.value.copy(action = action)
    }

    // ------------------------------------------------------------------
    // Running
    // ------------------------------------------------------------------

    private suspend fun queryWorkspace(workspace: WorkspaceFs, command: String): CodeGraphCommandResult {
        if (workspace is com.androidharness.app.workspace.SshFs) {
            val result = workspace.run("test -d .codegraph && $command", timeoutMs = 180_000, maxOutput = 80_000)
            return CodeGraphCommandResult(result.exitCode == 0, result.rawOutput + result.rawStderr +
                if (result.exitCode != 0) "\nCodeGraph must be installed and the project indexed on the SSH host." else "")
        }
        val ready = requireIndexed(workspace)
        if (ready != null) return ready
        val root = workspace.shellRoot!!
        return mcp.paused {
            val synced = run(CodeGraphCommands.sync, root, 180_000, 12_000)
            if (!synced.ok) CodeGraphCommandResult(false, "CodeGraph sync failed before the query:\n${synced.output}")
            else run(command, root, 180_000, 80_000)
        }
    }

    private suspend fun workspaceCommand(
        workspace: WorkspaceFs,
        command: String,
        label: String,
        timeoutMs: Int = 180_000,
    ): CodeGraphCommandResult {
        if (workspace is com.androidharness.app.workspace.SshFs) {
            val result = workspace.run(command, timeoutMs = timeoutMs, maxOutput = 40_000)
            return CodeGraphCommandResult(result.exitCode == 0, result.rawOutput + result.rawStderr)
        }
        val root = workspace.shellRoot
            ?: return refused("CodeGraph needs a workspace with a real filesystem path.")
        if (_state.value.version == null) refresh()
        if (_state.value.version == null) {
            return refused("Install CodeGraph in Settings → Code intelligence first.")
        }
        _workspaceState.value = CodeGraphRunState(busy = true, action = label)
        val result = mcp.paused { runWithProgress(root, command, timeoutMs, 40_000) }
        _workspaceState.value = CodeGraphRunState(
            message = result.output.ifBlank { if (result.ok) "$label complete." else "$label failed." },
            failed = !result.ok,
        )
        return result
    }

    /**
     * Runs a workspace command with its output redirected to a log file that is
     * read back while the command is still writing it, so the workspace card
     * shows what CodeGraph is doing instead of a spinner that never moves.
     *
     * The redirect carries the exit code through untouched (no pipe, no tee),
     * and works in every shell tier, including the privileged one whose runner
     * hands back a finished result rather than a stream.
     */
    private suspend fun runWithProgress(
        root: File,
        command: String,
        timeoutMs: Int,
        maxOutput: Int,
    ): CodeGraphCommandResult {
        val log = progressLog(root)
        withContext(Dispatchers.IO) { runCatching { log.delete() } }
        var offset = 0L
        val tail = StringBuilder()
        val result = coroutineScope {
            val ticker = launch {
                while (true) {
                    delay(PROGRESS_POLL_MS)
                    offset = readProgress(log, offset, tail)
                    if (tail.isNotEmpty()) {
                        _workspaceState.value = _workspaceState.value.copy(message = tail.trim().toString())
                    }
                }
            }
            try {
                run("$command > ${shellQuote(log.absolutePath)} 2>&1", root, timeoutMs, maxOutput)
            } finally {
                ticker.cancel()
            }
        }
        if (!log.isFile) {
            // No log means the redirect never took effect (a workspace this
            // shell cannot write) so the command never ran either: run it the
            // plain way so the button behaves exactly as it did before.
            return run(command, root, timeoutMs, maxOutput)
        }
        offset = readProgress(log, offset, tail)
        val text = tail.trim().toString()
        withContext(Dispatchers.IO) { runCatching { log.delete() } }
        // Whatever the shell tier added on its own (a degraded-tier warning)
        // arrives beside the log, not in it, and must survive.
        val note = result.output.trim()
        return CodeGraphCommandResult(
            result.ok,
            listOf(text, note).filter { it.isNotEmpty() }.joinToString("\n"),
        )
    }

    /**
     * Inside the index directory once it exists, and beside it during the very
     * first `init`, which is what creates it.
     */
    private fun progressLog(root: File): File =
        File(File(root, ".codegraph").takeIf { it.isDirectory } ?: root, CODEGRAPH_PROGRESS_LOG)

    /**
     * Appends whatever the log gained since [offset] onto [tail], keeping only
     * the last [PROGRESS_TAIL_CHARS]. Reading forward from an offset rather
     * than re-reading the file keeps a long index from copying its whole log
     * on every poll.
     */
    private suspend fun readProgress(log: File, offset: Long, tail: StringBuilder): Long =
        withContext(Dispatchers.IO) {
            runCatching {
                if (!log.isFile) return@runCatching offset
                java.io.RandomAccessFile(log, "r").use { raf ->
                    if (raf.length() <= offset) return@use offset
                    raf.seek(offset)
                    val bytes = ByteArray((raf.length() - offset).coerceAtMost(64_000L).toInt())
                    val read = raf.read(bytes)
                    if (read > 0) {
                        tail.append(String(bytes, 0, read).replace('\uFFFD', ' '))
                        if (tail.length > PROGRESS_TAIL_CHARS) {
                            tail.delete(0, tail.length - PROGRESS_TAIL_CHARS)
                        }
                    }
                    offset + read
                }
            }.getOrDefault(offset)
        }

    /** Reports a workspace run that never started, in the card that asked for it. */
    private fun refused(message: String): CodeGraphCommandResult {
        _workspaceState.value = CodeGraphRunState(message = message, failed = true)
        return CodeGraphCommandResult(false, message)
    }

    private suspend fun requireIndexed(workspace: WorkspaceFs): CodeGraphCommandResult? {
        val root = workspace.shellRoot
            ?: return CodeGraphCommandResult(false, "CodeGraph needs a workspace with a real filesystem path.")
        if (_state.value.version == null) refresh()
        if (_state.value.version == null) {
            return CodeGraphCommandResult(false, "CodeGraph is not installed. Open Settings → Code intelligence to install it.")
        }
        if (!root.resolve(".codegraph").isDirectory) {
            return CodeGraphCommandResult(false, "CodeGraph is not enabled for this workspace. Open Settings → Code intelligence and enable it first.")
        }
        return null
    }

    private suspend fun busy(label: String, block: suspend () -> CodeGraphCommandResult): CodeGraphState {
        _state.value = _state.value.copy(busy = true, action = label, message = null, failed = false)
        val result = runCatching { mcp.paused { block() } }.getOrElse {
            CodeGraphCommandResult(false, it.message ?: "$label failed.")
        }
        val refreshedVersion = if (result.ok) {
            if (binary.exists()) {
                val versionResult = run(CodeGraphCommands.version, home, 60_000, 4_000)
                if (versionResult.ok) parseVersion(versionResult.output) else markerVersion()
            } else null
        } else markerVersion()
        if (refreshedVersion == null) marker.delete() else marker.writeText(refreshedVersion)
        // Built from the CURRENT state, not the pre-run snapshot, so anything
        // the block recorded (the resolved release) survives. A vanished
        // install has no meaningful "latest" either.
        return _state.value.copy(
            version = refreshedVersion,
            latest = _state.value.latest.takeIf { refreshedVersion != null },
            busy = false,
            action = null,
            message = result.output.ifBlank { if (result.ok) "$label complete." else "$label failed." },
            failed = !result.ok,
        ).also { _state.value = it }
    }

    private suspend fun run(command: String, cwd: File, timeoutMs: Int, maxOutput: Int): CodeGraphCommandResult {
        val result = shellRouter.run(command, cwd, timeoutMs, maxOutput)
        val output = buildString {
            if (result.rawOutput.isNotBlank()) append(result.rawOutput.trimEnd())
            if (result.rawStderr.isNotBlank()) {
                if (isNotEmpty()) append('\n')
                append(result.rawStderr.trimEnd())
            }
            result.note?.let {
                if (isNotEmpty()) append('\n')
                append(it)
            }
        }
        return CodeGraphCommandResult(!result.timedOut && result.exitCode == 0, output)
    }

    private fun markerVersion(): String? =
        runCatching { marker.readText().trim().takeIf { it.isNotEmpty() } }.getOrNull()

    private fun parseVersion(output: String): String? = CodeGraphProvision.versionIn(output)
}